name: Node CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
    - run: npm install
    - run: npm run build
      env:
        CI: true
        HEADLESS: false
        PROGRESS: none
        NODE_ENV: pre
    - name: Publish to NPM
      run: npm publish || true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
