name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10.x, 12.x]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - run: npm install
    - run: npm run build
      env:
        CI: true
        HEADLESS: false
        PROGRESS: none
        NODE_ENV: test
    - name: Publish to NPM
      run: npm publish || true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
