name: build
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          npm run build
      - name: Build
        run: |
          npm publish

