name: build
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: | 
          yarn
      - name: Build
        run: |
          yarn build
      - name: publish
        run: |
          yarn publish

