
name: Node.js Package
on:
   push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn run build
<<<<<<< HEAD
=======
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
>>>>>>> 984d554150a27a23819c407df484fd7fe664e393
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
