
name: Node.js Package
on:
   push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: git config --global user.email "${{ secrets.WORKFLOW_COMMIT_EMAIL }}"
      - run: git config --global user.name "${{ secrets.WORKFLOW_COMMIT_NAME }}"
      - run: yarn version --patch
      - run: yarn install
      - run: yarn run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}